export const location2Data = {
  1: [{ value: 0, label: "전체" }],
  2: [
    { value: 0, label: "전체" },
    { value: 1, label: "강남구" },
    { value: 2, label: "강동구" },
    { value: 3, label: "강북구" },
    { value: 4, label: "강서구" },
    { value: 5, label: "관악구" },
    { value: 6, label: "광진구" },
    { value: 7, label: "구로구" },
    { value: 8, label: "금천구" },
    { value: 9, label: "노원구" },
    { value: 10, label: "도봉구" },
    { value: 11, label: "동대문구" },
    { value: 12, label: "동작구" },
    { value: 13, label: "마포구" },
    { value: 14, label: "서대문구" },
    { value: 15, label: "서초구" },
    { value: 16, label: "성동구" },
    { value: 17, label: "성북구" },
    { value: 18, label: "송파구" },
    { value: 19, label: "양천구" },
    { value: 20, label: "영등포구" },
    { value: 21, label: "용산구" },
    { value: 22, label: "은평구" },
    { value: 23, label: "종로구" },
    { value: 24, label: "중구" },
    { value: 25, label: "중랑구" }
  ],
  3: [
    { value: 0, label: "전체" },
    { value: 1, label: "중구" },
    { value: 2, label: "서구" },
    { value: 3, label: "동구" },
    { value: 4, label: "영도구" },
    { value: 5, label: "부산진구" },
    { value: 6, label: "동래구" },
    { value: 7, label: "남구" },
    { value: 8, label: "북구" },
    { value: 9, label: "강서구" },
    { value: 10, label: "해운대구" },
    { value: 11, label: "사하구" },
    { value: 12, label: "금정구" },
    { value: 13, label: "연제구" },
    { value: 14, label: "수영구" },
    { value: 15, label: "사상구" },
    { value: 16, label: "기장군" }
  ],
  4: [
    { value: 0, label: "전체" },
    { value: 1, label: "중구" },
    { value: 2, label: "동구" },
    { value: 3, label: "서구" },
    { value: 4, label: "남구" },
    { value: 5, label: "북구" },
    { value: 6, label: "수성구" },
    { value: 7, label: "달서구" },
    { value: 8, label: "달성군" },
    { value: 9, label: "군위군" }
  ],
  5: [
    { value: 0, label: "전체" },
    { value: 1, label: "중구" },
    { value: 2, label: "동구" },
    { value: 3, label: "미추홀구" },
    { value: 4, label: "연수구" },
    { value: 5, label: "남동구" },
    { value: 6, label: "부평구" },
    { value: 7, label: "계양구" },
    { value: 8, label: "서구" },
    { value: 9, label: "강화군" },
    { value: 10, label: "옹진군" }
  ],
  6: [
    { value: 0, label: "전체" },
    { value: 1, label: "동구" },
    { value: 2, label: "서구" },
    { value: 3, label: "남구" },
    { value: 4, label: "북구" },
    { value: 5, label: "광산구" }
  ],
  7: [
    { value: 0, label: "전체" },
    { value: 1, label: "동구" },
    { value: 2, label: "중구" },
    { value: 3, label: "서구" },
    { value: 4, label: "유성구" },
    { value: 5, label: "대덕구" }
  ],
  8: [
    { value: 0, label: "전체" },
    { value: 1, label: "중구" },
    { value: 2, label: "남구" },
    { value: 3, label: "동구" },
    { value: 4, label: "북구" },
    { value: 5, label: "울주군" }
  ],
  9: [
    { value: 0, label: "전체" },
    { value: 1, label: "조치원읍" },
    { value: 2, label: "연기면" },
    { value: 3, label: "연동면" },
    { value: 4, label: "부강면" },
    { value: 5, label: "금남면" },
    { value: 6, label: "장군면" },
    { value: 7, label: "연서면" },
    { value: 8, label: "전의면" },
    { value: 9, label: "전동면" },
    { value: 10, label: "소정면" },
    { value: 11, label: "한솔동" },
    { value: 12, label: "새롬동" },
    { value: 13, label: "나성동" },
    { value: 14, label: "도담동" },
    { value: 15, label: "어진동" },
    { value: 16, label: "해밀동" },
    { value: 17, label: "아름동" },
    { value: 18, label: "종촌동" },
    { value: 19, label: "고운동" },
    { value: 20, label: "소담동" },
    { value: 21, label: "반곡동" },
    { value: 22, label: "보람동" },
    { value: 23, label: "대평동" },
    { value: 24, label: "다정동" }
  ],
  10: [
    { value: 0, label: "전체" },
    { value: 1, label: "수원시" },
    { value: 2, label: "성남시" },
    { value: 3, label: "의정부시" },
    { value: 4, label: "안양시" },
    { value: 5, label: "부천시" },
    { value: 6, label: "광명시" },
    { value: 7, label: "평택시" },
    { value: 8, label: "동두천시" },
    { value: 9, label: "안산시" },
    { value: 10, label: "고양시" },
    { value: 11, label: "과천시" },
    { value: 12, label: "구리시" },
    { value: 13, label: "남양주시" },
    { value: 14, label: "오산시" },
    { value: 15, label: "시흥시" },
    { value: 16, label: "군포시" },
    { value: 17, label: "의왕시" },
    { value: 18, label: "하남시" },
    { value: 19, label: "용인시" },
    { value: 20, label: "파주시" },
    { value: 21, label: "이천시" },
    { value: 22, label: "안성시" },
    { value: 23, label: "김포시" },
    { value: 24, label: "화성시" },
    { value: 25, label: "광주시" },
    { value: 26, label: "양주시" },
    { value: 27, label: "포천시" },
    { value: 28, label: "여주시" },
    { value: 29, label: "연천군" },
    { value: 30, label: "가평군" },
    { value: 31, label: "양평군" }
  ],
  11: [
    { value: 0, label: "전체" },
    { value: 1, label: "춘천" },
    { value: 2, label: "원주" },
    { value: 3, label: "강릉" },
    { value: 4, label: "동해" },
    { value: 5, label: "태백" },
    { value: 6, label: "속초" },
    { value: 7, label: "삼척" },
    { value: 8, label: "홍천" },
    { value: 9, label: "영월" },
    { value: 10, label: "평창" },
    { value: 11, label: "정선" },
    { value: 12, label: "철원" },
    { value: 13, label: "화천" },
    { value: 14, label: "양구" },
    { value: 15, label: "인제" },
    { value: 16, label: "고성" },
    { value: 17, label: "양양" }
  ],
  12: [
    { value: 0, label: "전체" },
    { value: 1, label: "청주" },
    { value: 2, label: "충주" },
    { value: 3, label: "제천" },
    { value: 4, label: "보은" },
    { value: 5, label: "옥천" },
    { value: 6, label: "영동" },
    { value: 7, label: "증평" },
    { value: 8, label: "진천" },
    { value: 9, label: "괴산" },
    { value: 10, label: "음성" },
    { value: 11, label: "단양" }
  ],
  13: [
    { value: 0, label: "전체" },
    { value: 1, label: "천안" },
    { value: 2, label: "공주" },
    { value: 3, label: "보령" },
    { value: 4, label: "아산" },
    { value: 5, label: "서산" },
    { value: 6, label: "논산" },
    { value: 7, label: "계룡" },
    { value: 8, label: "당진" },
    { value: 9, label: "금산" },
    { value: 10, label: "부여" },
    { value: 11, label: "서천" },
    { value: 12, label: "청양" },
    { value: 13, label: "홍성" },
    { value: 14, label: "예산" },
    { value: 15, label: "태안" }
  ],
  14: [
    { value: 0, label: "전체" },
    { value: 1, label: "전주" },
    { value: 2, label: "익산" },
    { value: 3, label: "군산" },
    { value: 4, label: "정읍" },
    { value: 5, label: "남원" },
    { value: 6, label: "김제" },
    { value: 7, label: "무주" },
    { value: 8, label: "완주" },
    { value: 9, label: "부안" },
    { value: 10, label: "고창" },
    { value: 11, label: "임실" },
    { value: 12, label: "순창" },
    { value: 13, label: "진안" },
    { value: 14, label: "장수" }
  ],
  15: [
    { value: 0, label: "전체" },
    { value: 1, label: "목포" },
    { value: 2, label: "여수" },
    { value: 3, label: "순천" },
    { value: 4, label: "나주" },
    { value: 5, label: "광양" },
    { value: 6, label: "담양" },
    { value: 7, label: "곡성" },
    { value: 8, label: "구례" },
    { value: 9, label: "고흥" },
    { value: 10, label: "보성" },
    { value: 11, label: "화순" },
    { value: 12, label: "장흥" },
    { value: 13, label: "강진" },
    { value: 14, label: "해남" },
    { value: 15, label: "영암" },
    { value: 16, label: "무안" },
    { value: 17, label: "함평" },
    { value: 18, label: "영광" },
    { value: 19, label: "장성" },
    { value: 20, label: "완도" },
    { value: 21, label: "진도" },
    { value: 22, label: "신안" }
  ],
  16: [
    { value: 0, label: "전체" },
    { value: 1, label: "포항" },
    { value: 2, label: "경주" },
    { value: 3, label: "김천" },
    { value: 4, label: "안동" },
    { value: 5, label: "구미" },
    { value: 6, label: "영주" },
    { value: 7, label: "영천" },
    { value: 8, label: "상주" },
    { value: 9, label: "문경" },
    { value: 10, label: "경산" },
    { value: 11, label: "의성" },
    { value: 12, label: "청송" },
    { value: 13, label: "영양" },
    { value: 14, label: "영덕" },
    { value: 15, label: "청도" },
    { value: 16, label: "고령" },
    { value: 17, label: "성주" },
    { value: 18, label: "칠곡" },
    { value: 19, label: "예천" },
    { value: 20, label: "봉화" },
    { value: 21, label: "울진" },
    { value: 22, label: "울릉" }
  ],
  17: [
    { value: 0, label: "전체" },
    { value: 1, label: "창원" },
    { value: 2, label: "김해" },
    { value: 3, label: "양산" },
    { value: 4, label: "진주" },
    { value: 5, label: "거제" },
    { value: 6, label: "통영" },
    { value: 7, label: "사천" },
    { value: 8, label: "밀양" },
    { value: 9, label: "함안" },
    { value: 10, label: "거창" },
    { value: 11, label: "창녕" },
    { value: 12, label: "고성" },
    { value: 13, label: "하동" },
    { value: 14, label: "합천" },
    { value: 15, label: "남해" },
    { value: 16, label: "함양" },
    { value: 17, label: "신창" },
    { value: 18, label: "의령" }
  ],
  18: [
    { value: 0, label: "전체" },
    { value: 1, label: "제주도" },
    { value: 2, label: "서귀포시" }
  ]
};

  
  
  export const location1Data = {
    1: ["전체"],
    2: ["서울특별시"],
    3: ["부산광역시"],
    4: ["대구광역시"],
    5: ["인천광역시"],
    6: ["광주광역시"],
    7: ["대전광역시"],
    8: ["울산광역시"],
    9: ["세종특별자치시"],
    10: ["경기도"],
    11: ["강원도"],
    12: ["충청북도"],
    13: ["충청남도"],
    14: ["전라북도"],
    15: ["전라남도"],
    16: ["경상북도"],
    17: ["경상남도"],
    18: ["제주도"]
  };